#!/usr/bin/env bash
# Idempotent bootstrap for a personal claude-config repo.
#
#   bootstrap.sh                 install / re-sync into ~/.claude/
#   bootstrap.sh --dry-run       print actions, change nothing
#   bootstrap.sh --force         allow overwriting a hand-edited settings.json
#   bootstrap.sh --skip-validate skip source validation
#   bootstrap.sh validate        run validation checks only, no install
#   bootstrap.sh bundle <name> <target-dir>
#                                stamp a skill bundle into another repo's .claude/
#
# A "bundle" is a skills/<name>/ dir containing a `.bundle` marker file. Bundles
# are NOT linked globally (so they don't inflate every project's skill list);
# install them per-project with `bundle <name> <target-dir>`.
#
# Generated by configure-claude. Safe to edit and re-run.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${HOME}/.claude"
LAST_RENDER="${CLAUDE_DIR}/.last-rendered-settings.json"
BACKUP_KEEP=3

DRY_RUN=0
FORCE=0
SKIP_VALIDATE=0

# ---- helpers ----------------------------------------------------------------

say()  { printf '%s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

run() {
  if (( DRY_RUN )); then say "  [dry-run] $*"; else "$@"; fi
}

need() { command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"; }

# Extract a top-level YAML frontmatter scalar from a markdown file.
yaml_field() {
  local file="$1" field="$2"
  awk -v field="$field" '
    BEGIN { in_fm = 0; pat = "^[[:space:]]*" field "[[:space:]]*:[[:space:]]*" }
    /^---[[:space:]]*$/ { in_fm++; if (in_fm == 2) exit; next }
    in_fm == 1 && $0 ~ pat {
      v = $0; sub(pat, "", v)
      sub(/^["'"'"']/, "", v); sub(/["'"'"']$/, "", v)
      print v; exit
    }
  ' "$file"
}

# ---- validation -------------------------------------------------------------

validate() {
  local fail=0

  # Frontmatter `name` matches folder (skills) / filename (agents).
  if [[ -d "${REPO}/skills" ]]; then
    while IFS= read -r -d '' f; do
      local name expected
      name=$(yaml_field "$f" name)
      expected="$(basename "$(dirname "$f")")"
      if [[ -z "$name" ]]; then warn "missing frontmatter name: $f"; fail=1
      elif [[ "$name" != "$expected" ]]; then
        warn "name mismatch in $f: frontmatter='$name' folder='$expected'"; fail=1
      fi
    done < <(find "${REPO}/skills" -type f -name 'SKILL.md' -print0)
  fi

  if [[ -d "${REPO}/agents" ]]; then
    while IFS= read -r -d '' f; do
      local name expected
      name=$(yaml_field "$f" name)
      expected="$(basename "$f" .md)"
      if [[ -z "$name" ]]; then warn "missing frontmatter name: $f"; fail=1
      elif [[ "$name" != "$expected" ]]; then
        warn "name mismatch in $f: frontmatter='$name' file='$expected'"; fail=1
      fi
    done < <(find "${REPO}/agents" -type f -name '*.md' -print0)
  fi

  # Hooks referenced in settings.template.json exist and are executable.
  if [[ -f "${REPO}/settings.template.json" ]]; then
    local hook_paths
    hook_paths=$(jq -r '
      [.. | objects | select(has("command")) | .command]
      | map(capture("\"(?<p>[^\"]+\\.sh)\"")? // empty | .p) | .[]?
    ' "${REPO}/settings.template.json" 2>/dev/null || true)
    while IFS= read -r p; do
      [[ -z "$p" ]] && continue
      local resolved="${p//__REPO__/$REPO}"
      if [[ ! -f "$resolved" ]]; then warn "hook referenced but missing: $resolved"; fail=1
      elif [[ ! -x "$resolved" ]]; then warn "hook not executable: $resolved"; fail=1
      fi
    done <<< "$hook_paths"
  fi

  # Rules declare a non-empty paths: frontmatter.
  if [[ -d "${REPO}/rules" ]]; then
    for f in "${REPO}/rules"/*.md; do
      [[ -e "$f" ]] || continue
      if ! awk '/^---[[:space:]]*$/{c++} c==1 && /^paths:/{found=1} c==1 && found && /^[[:space:]]+- /{has=1} END{exit !has}' "$f"; then
        warn "rule has empty or missing paths: $f"; fail=1
      fi
    done
  fi

  (( fail )) && die "validation failed; fix the issues above or pass --skip-validate"
  say "  validation: ok"
}

# ---- install ----------------------------------------------------------------

link() {
  local src="$1" dest="$2"
  if [[ -L "$dest" ]]; then run ln -sfn "$src" "$dest"
  elif [[ -e "$dest" ]]; then warn "SKIP (real file exists, not overwriting): $dest"; return
  else run ln -s "$src" "$dest"; fi
}

# Remove dangling symlinks under $1 that point inside $REPO but to a missing target.
prune_stale() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  while IFS= read -r -d '' link_path; do
    local target; target=$(readlink "$link_path")
    [[ "$target" == "$REPO"/* ]] || continue
    [[ -e "$target" ]] && continue
    run rm -f "$link_path"
    say "  pruned stale: $link_path"
  done < <(find "$dir" -maxdepth 2 -type l -print0)
}

install_agents() {
  [[ -d "${REPO}/agents" ]] || return 0
  say "Linking agents:"
  while IFS= read -r -d '' f; do
    link "$f" "${CLAUDE_DIR}/agents/$(basename "$f")"
  done < <(find "${REPO}/agents" -type f -name '*.md' -print0)
}

# Skill dirs that are NOT inside a bundle (no .bundle marker on the way up).
global_skill_dirs() {
  [[ -d "${REPO}/skills" ]] || return 0
  while IFS= read -r -d '' skill_md; do
    local skill_dir check; skill_dir="$(dirname "$skill_md")"; check="$skill_dir"
    while [[ "$check" != "${REPO}/skills" && "$check" != "/" ]]; do
      if [[ -f "${check}/.bundle" ]]; then skill_dir=""; break; fi
      check="$(dirname "$check")"
    done
    [[ -n "$skill_dir" ]] && printf '%s\n' "$skill_dir"
  done < <(find "${REPO}/skills" -type f -name 'SKILL.md' -print0)
}

install_skills() {
  [[ -d "${REPO}/skills" ]] || return 0
  say "Linking global skills (bundles excluded):"
  local desired; desired=$(mktemp)
  global_skill_dirs | while IFS= read -r d; do
    printf '%s\t%s\n' "$(basename "$d")" "$d"
  done > "$desired"

  if [[ -d "${CLAUDE_DIR}/skills" ]]; then
    while IFS= read -r -d '' link_path; do
      local target name; target=$(readlink "$link_path")
      [[ "$target" == "$REPO"/* ]] || continue
      name="$(basename "$link_path")"
      if ! awk -F'\t' -v n="$name" '$1==n{f=1} END{exit !f}' "$desired"; then
        run rm -f "$link_path"; say "  pruned (bundled or removed): $link_path"
      fi
    done < <(find "${CLAUDE_DIR}/skills" -maxdepth 1 -type l -print0)
  fi

  while IFS=$'\t' read -r name src; do
    [[ -z "$name" ]] && continue
    link "$src" "${CLAUDE_DIR}/skills/${name}"
  done < "$desired"
  rm -f "$desired"
}

render_rules() {
  [[ -d "${REPO}/rules" ]] || return 0
  say "Rendering path-scoped rules:"
  for f in "${REPO}/rules"/*.md; do
    [[ -e "$f" ]] || continue
    local dest tmp; dest="${CLAUDE_DIR}/rules/$(basename "$f")"; tmp=$(mktemp)
    awk -v repo="$REPO" '{ gsub(/__REPO__/, repo); print }' "$f" > "$tmp"
    if [[ -L "$dest" ]]; then run rm -f "$dest"; fi
    if [[ ! -e "$dest" ]] || ! cmp -s "$tmp" "$dest"; then
      if (( DRY_RUN )); then say "  [dry-run] write: $dest"; rm -f "$tmp"
      else mv "$tmp" "$dest"; say "  wrote: $dest"; fi
    else rm -f "$tmp"; fi
  done
}

render_settings() {
  [[ -f "${REPO}/settings.template.json" ]] || return 0
  say "Rendering settings.json:"
  local dest="${CLAUDE_DIR}/settings.json" tmp; tmp=$(mktemp)
  awk -v repo="$REPO" '{ gsub(/__REPO__/, repo); print }' "${REPO}/settings.template.json" > "$tmp"
  jq -e . "$tmp" >/dev/null || { rm -f "$tmp"; die "rendered settings.json is not valid JSON"; }

  if [[ -L "$dest" ]]; then run rm -f "$dest"; fi

  if [[ ! -e "$dest" ]]; then
    if (( DRY_RUN )); then say "  [dry-run] write: $dest"; rm -f "$tmp"; return; fi
    mv "$tmp" "$dest"; cp "$dest" "$LAST_RENDER"; say "  wrote: $dest"; return
  fi

  if cmp -s "$tmp" "$dest"; then
    (( DRY_RUN )) || cp "$tmp" "$LAST_RENDER"; rm -f "$tmp"; say "  unchanged: $dest"; return
  fi

  if [[ -f "$LAST_RENDER" ]] && ! cmp -s "$dest" "$LAST_RENDER"; then
    if (( ! FORCE )); then
      warn "${dest} has drifted from the last render — refusing to overwrite."
      diff -u "$dest" "$tmp" >&2 || true
      rm -f "$tmp"; die "re-run with --force to overwrite, or reconcile manually."
    fi
    say "  (--force) overwriting hand-edited settings.json"
  fi

  if (( DRY_RUN )); then say "  [dry-run] would update: $dest"; rm -f "$tmp"; return; fi

  local backup="${dest}.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$dest" "$backup"; mv "$tmp" "$dest"; cp "$dest" "$LAST_RENDER"
  say "  rewrote: $dest (previous saved as $backup)"

  local -a backups=()
  while IFS= read -r b; do backups+=("$b"); done < <(ls -1t "${dest}".bak.* 2>/dev/null || true)
  if (( ${#backups[@]} > BACKUP_KEEP )); then
    for old in "${backups[@]:$BACKUP_KEEP}"; do rm -f "$old"; say "  rotated out: $old"; done
  fi
}

install_user_claudemd() {
  [[ -f "${REPO}/user-CLAUDE.md" ]] || return 0
  say "Linking user-global CLAUDE.md:"
  link "${REPO}/user-CLAUDE.md" "${CLAUDE_DIR}/CLAUDE.md"
}

ensure_executable_hooks() {
  [[ -d "${REPO}/hooks" ]] || return 0
  find "${REPO}/hooks" -type f -name '*.sh' -exec chmod +x {} + 2>/dev/null || true
}

# ---- bundle subcommand ------------------------------------------------------

cmd_bundle() {
  local name="${1:-}" target="${2:-}"
  [[ -n "$name" && -n "$target" ]] || die "usage: bootstrap.sh bundle <name> <target-dir>"
  local bundle_dir="${REPO}/skills/${name}"
  [[ -d "$bundle_dir" ]] || die "no such bundle: $bundle_dir"
  [[ -f "${bundle_dir}/.bundle" ]] || die "not a bundle (missing ${bundle_dir}/.bundle)"
  [[ -d "$target" ]] || die "target dir does not exist: $target"

  local skills_dir="${target}/.claude/skills"
  run mkdir -p "$skills_dir"
  say "Stamping bundle '${name}' → ${skills_dir}:"
  while IFS= read -r -d '' skill_md; do
    local skill_dir; skill_dir="$(dirname "$skill_md")"
    link "$skill_dir" "${skills_dir}/$(basename "$skill_dir")"
  done < <(find "$bundle_dir" -mindepth 2 -name 'SKILL.md' -print0)
  say "Done. Skills are live next time Claude Code starts in ${target}."
}

# ---- main -------------------------------------------------------------------

main() {
  need jq; need awk; need find

  local subcmd="" args=()
  while (( $# )); do
    case "$1" in
      --dry-run) DRY_RUN=1 ;;
      --force) FORCE=1 ;;
      --skip-validate) SKIP_VALIDATE=1 ;;
      bundle|validate) subcmd="$1"; shift; args=("$@"); break ;;
      -h|--help) sed -n '2,18p' "${BASH_SOURCE[0]}"; exit 0 ;;
      *) die "unknown argument: $1" ;;
    esac
    shift
  done

  case "$subcmd" in
    bundle) cmd_bundle "${args[@]}"; exit 0 ;;
    validate) validate; exit 0 ;;
  esac

  ensure_executable_hooks
  run mkdir -p "${CLAUDE_DIR}/agents" "${CLAUDE_DIR}/rules" "${CLAUDE_DIR}/skills"

  if (( ! SKIP_VALIDATE )); then say "Validating sources:"; validate; fi

  say "Pruning stale symlinks:"
  prune_stale "${CLAUDE_DIR}/agents"
  prune_stale "${CLAUDE_DIR}/skills"
  prune_stale "${CLAUDE_DIR}/rules"

  install_agents
  install_skills
  install_user_claudemd
  render_rules
  render_settings

  say "Done."
}

main "$@"
